### ISSUE TITLE
Unable to install dependencies

### ISSUE THREAD

**Issue by chennakeshava1998** [crazydonkey200/neural-symbolic-machines#18]
Can you please specify the configuration of the emvironment? I am using Anaconda2(because python2 is required) package manager. All the libraries in requirements.txt have been successfully installed.

Specifically, I'm running into this error:

```
Traceback (most recent call last):
  File "../experiment.py", line 29, in <module>
    from nsm import word_embeddings
  File "/home/16co108/mapo/projects/neural-symbolic-machines/table/wikisql/nsm/word_embeddings.py", line 3, in <module>
    import gensim
  File "/home/16co108/.local/lib/python2.7/site-packages/gensim/__init__.py", line 6, in <module>
    from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization, utils  # noqa:F401
  File "/home/16co108/.local/lib/python2.7/site-packages/gensim/parsing/__init__.py", line 4, in <module>
    from .preprocessing import (remove_stopwords, strip_punctuation, strip_punctuation2,  # noqa:F401
  File "/home/16co108/.local/lib/python2.7/site-packages/gensim/parsing/preprocessing.py", line 40, in <module>
    from gensim import utils
  File "/home/16co108/.local/lib/python2.7/site-packages/gensim/utils.py", line 41, in <module>
    import scipy.sparse
  File "/opt/ohpc/pub/anaconda2/5.0.1/lib/python2.7/site-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .csr import *
  File "/opt/ohpc/pub/anaconda2/5.0.1/lib/python2.7/site-packages/scipy/sparse/csr.py", line 15, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/ohpc/pub/anaconda2/5.0.1/lib/python2.7/site-packages/scipy/sparse/_sparsetools.so)
Traceback (most recent call last):
  File "../experiment.py", line 29, in <module>
    from nsm import word_embeddings
  File "/home/16co108/mapo/projects/neural-symbolic-machines/table/wikisql/nsm/word_embeddings.py", line 3, in <module>
    import gensim
  File "/home/16co108/.local/lib/python2.7/site-packages/gensim/__init__.py", line 6, in <module>
    from gensim import parsing, matutils, interfaces, corpora, models, similarities, summarization, utils  # noqa:F401
  File "/home/16co108/.local/lib/python2.7/site-packages/gensim/parsing/__init__.py", line 4, in <module>
    from .preprocessing import (remove_stopwords, strip_punctuation, strip_punctuation2,  # noqa:F401
  File "/home/16co108/.local/lib/python2.7/site-packages/gensim/parsing/preprocessing.py", line 40, in <module>
    from gensim import utils
  File "/home/16co108/.local/lib/python2.7/site-packages/gensim/utils.py", line 41, in <module>
    import scipy.sparse
  File "/opt/ohpc/pub/anaconda2/5.0.1/lib/python2.7/site-packages/scipy/sparse/__init__.py", line 229, in <module>
    from .csr import *
  File "/opt/ohpc/pub/anaconda2/5.0.1/lib/python2.7/site-packages/scipy/sparse/csr.py", line 15, in <module>
    from ._sparsetools import csr_tocsc, csr_tobsr, csr_count_blocks, \
ImportError: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /opt/ohpc/pub/anaconda2/5.0.1/lib/python2.7/site-packages/scipy/sparse/_sparsetools.so)

```

**Comment by crazydonkey200** [comment]
Hi, I am using pip+virtualenv to manage my environments. The error you report here seems to be a problem with conda. There was a similar issue and a solution proposed [here.](https://github.com/AllenDowney/ThinkStats2/issues/92) 

Here's a quote from the above url.  

"In my case I use Anaconda, and the problem is solved with `conda install libgcc`, which upgrades the current gcc compiler."

**Comment by chennakeshava1998** [comment]
Hi, thanks for the update. The conda command was not useful(I am using anaconda2 in centOS). I could resolve the issue by adding `--no-site-packages` flag during creation of virtual environment. The problem with dependencies arose because python was using numpy in my system, and it never installed numpy in the virtual env.

Thanks again.
