### ISSUE TITLE
training stop 

### ISSUE THREAD

**Issue by guotong1988** [crazydonkey200/neural-symbolic-machines#23]
I have edit the whole code to python3.

And the program stop here:
![image](https://user-images.githubusercontent.com/4702353/58773970-e8bfb080-85f1-11e9-919c-8ce7da1405a7.png)

`ctrl + c` shows
```
  File "experiment_mapo.py", line 1274, in <module>
    tf.app.run()
  File "/data4/tong.guo/Py36/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "experiment_mapo.py", line 1270, in main
    run_experiment()
  File "experiment_mapo.py", line 704, in run_experiment
    actor.join()
  File "/data4/tong.guo/Py36/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "/data4/tong.guo/Py36/lib/python3.6/multiprocessing/popen_fork.py", line 50, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/data4/tong.guo/Py36/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
```

and 

```
Process actor_15:
Process actor_3:
Process actor_14:
Traceback (most recent call last):
Process actor_6:
  File "/data4/tong.guo/Py36/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Traceback (most recent call last):
  File "/data4/tong.guo/Py36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "experiment_mapo.py", line 962, in run
    new_ckpt = self.ckpt_queue.get()
  File "/data4/tong.guo/Py36/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/data4/tong.guo/Py36/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
Traceback (most recent call last):
  File "/data4/tong.guo/Py36/lib/python3.6/multiprocessing/process.py", line 261, in _bootstrap
    util._exit_function()
  File "/data4/tong.guo/Py36/lib/python3.6/multiprocessing/util.py", line 322, in _exit_function
    _run_finalizers()
  File "/data4/tong.guo/Py36/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/data4/tong.guo/Py36/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/data4/tong.guo/Py36/lib/python3.6/multiprocessing/queues.py", line 191, in _finalize_join
    thread.join()
  File "/data4/tong.guo/Py36/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/data4/tong.guo/Py36/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "experiment_mapo.py", line 962, in run
    new_ckpt = self.ckpt_queue.get()
  File "/data4/tong.guo/Py36/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
  File "/data4/tong.guo/Py36/lib/python3.6/multiprocessing/queues.py", line 93, in get
    with self._rlock:
  File "/data4/tong.guo/Py36/lib/python3.6/multiprocessing/synchronize.py", line 96, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt

```

**Comment by guotong1988** [comment]
The config:
```
FLAGS = tf.app.flags.FLAGS  


# Experiment name
tf.flags.DEFINE_string('output_dir', '../output_dir', 'output folder.')
tf.flags.DEFINE_string('experiment_name', 'experiment',
                       'All outputs of this experiment is'
                       ' saved under a folder with the same name.')


# Tensorboard logging
tf.app.flags.DEFINE_string(
  'tb_log_dir', '', 'Path for saving tensorboard logs.')


# Tensorflow model checkpoint.
tf.app.flags.DEFINE_string(
  'saved_model_dir', 'saved_model', 'Path for saving models.')
tf.app.flags.DEFINE_string(
  'best_model_dir', 'best_model', 'Path for saving best models.')
tf.app.flags.DEFINE_string(
  'init_model_path', '', 'Path for saving best models.')
tf.app.flags.DEFINE_string(
  'meta_graph_path', '', 'Path for meta graph.')
tf.app.flags.DEFINE_string('experiment_to_eval', '', '.')


# Model
## Computer
tf.app.flags.DEFINE_integer(
  'max_n_mem', 60, 'Max number of memory slots in the "computer".')
tf.app.flags.DEFINE_integer(
  'max_n_exp', 4, 'Max number of expressions allowed in a program.')
tf.app.flags.DEFINE_integer(
  'max_n_valid_indices', 60, 'Max number of valid tokens during decoding.')
tf.app.flags.DEFINE_bool(
  'use_cache', True, 'Use cache to avoid generating the same samples.')
tf.app.flags.DEFINE_string(
  'en_vocab_file', '../wikisql_data/processed_input/preprocess_2/en_vocab_min_count_5.json', '.')
tf.app.flags.DEFINE_string(
  'executor', 'wikisql', 'Which executor to use, wtq or wikisql.')


## neural network
tf.app.flags.DEFINE_integer(
  'hidden_size', 200, 'Number of hidden units.')
tf.app.flags.DEFINE_integer(
  'attn_size', 200, 'Size of attention vector.')
tf.app.flags.DEFINE_integer(
  'attn_vec_size', 200, 'Size of the vector parameter for computing attention.')
tf.app.flags.DEFINE_integer(
  'n_layers', 2, 'Number of layers in decoder.')
tf.app.flags.DEFINE_integer(
  'en_n_layers', 2, 'Number of layers in encoder.')
tf.app.flags.DEFINE_integer(
  'en_embedding_size', 200, 'Size of encoder input embedding.')
tf.app.flags.DEFINE_integer(
  'value_embedding_size', 300, 'Size of value embedding for the constants.')
tf.app.flags.DEFINE_bool(
  'en_bidirectional', True, 'Whether to use bidirectional RNN in encoder.')
tf.app.flags.DEFINE_bool(
  'en_attn_on_constants', False, '.')
tf.app.flags.DEFINE_bool(
  'use_pretrained_embeddings', True, 'Whether to use pretrained embeddings.')
tf.app.flags.DEFINE_integer(
  'pretrained_embedding_size', 300, 'Size of pretrained embedding.')


# Features
tf.app.flags.DEFINE_integer(
  'n_de_output_features', 1,
  'Number of features in decoder output softmax.')
tf.app.flags.DEFINE_integer(
  'n_en_input_features', 1,
  'Number of features in encoder inputs.')


# Data
tf.app.flags.DEFINE_string(
  'table_file', '../wikisql_data/processed_input/preprocess_2/tables.jsonl', 'Path to the file of wikitables, a jsonl file.')
tf.app.flags.DEFINE_string(
  'train_file', '', 'Path to the file of training examples, a jsonl file.')
tf.app.flags.DEFINE_string(
  'dev_file', '../wikisql_data/processed_input/preprocess_2/dev_split.jsonl', 'Path to the file of training examples, a jsonl file.')
tf.app.flags.DEFINE_string(
  'eval_file', '', 'Path to the file of test examples, a jsonl file.')
tf.app.flags.DEFINE_string(
  'embedding_file', '../wikisql_data/raw_input/wikisql_glove_embedding_mat.npy', 'Path to the file of pretrained embeddings, a npy file.')
tf.app.flags.DEFINE_string(
  'vocab_file', '../wikisql_data/raw_input/wikisql_glove_vocab.json', 'Path to the vocab file for the pretrained embeddings, a json file.')
tf.app.flags.DEFINE_string(
  'train_shard_dir', '../wikisql_data/processed_input/preprocess_2/', 'Folder containing the sharded training data.')
tf.app.flags.DEFINE_string(
  'train_shard_prefix', 'train_split_shard_30-', 'The prefix for the sharded files.')
tf.app.flags.DEFINE_integer(
  'n_train_shard', 90, 'Number of shards in total.')
tf.app.flags.DEFINE_integer(
  'shard_start', 0,
  'Start id of the shard to use.')
tf.app.flags.DEFINE_integer(
  'shard_end', 30, 'End id of the shard to use.')


# Load saved samples.
tf.app.flags.DEFINE_bool(
  'load_saved_programs', True,
  'Whether to use load saved programs from exploration.')
tf.app.flags.DEFINE_string(
  'saved_program_file', '../wikisql_data/processed_input/preprocess_2/all_train_saved_programs-1k_5.json', 'Saved program file.')


# Training
tf.app.flags.DEFINE_integer(
  'n_steps', 15000, 'Maximum number of steps in training.')
tf.app.flags.DEFINE_integer(
  'n_explore_samples', 1, 'Number of exploration samples per env per epoch.')
tf.app.flags.DEFINE_integer(
  'n_extra_explore_for_hard', 9, 'Number of exploration samples for hard envs.')
tf.app.flags.DEFINE_float(
  'learning_rate', 0.001, 'Initial learning rate.')
tf.app.flags.DEFINE_float(
  'max_grad_norm', 5.0, 'Maximum gradient norm.')
tf.app.flags.DEFINE_float(
  'l2_coeff', 0.0, 'l2 regularization coefficient.')
tf.app.flags.DEFINE_float(
  'dropout', 0.0, 'Dropout rate.')
tf.app.flags.DEFINE_integer(
  'batch_size', 750, 'Model batch size.')
tf.app.flags.DEFINE_integer(
  'n_actors', 30, 'Number of actors for generating samples.')
tf.app.flags.DEFINE_integer(
  'save_every_n', 10,
  'Save model to a ckpt every n train steps, -1 means save every epoch.')
tf.app.flags.DEFINE_bool(
  'save_replay_buffer_at_end', True,
  'Whether to save the full replay buffer for each actor at the '
  'end of training or not')
tf.app.flags.DEFINE_integer(
  'log_samples_every_n_epoch', 0,
  'Log samples every n epochs.')
tf.app.flags.DEFINE_bool(
  'greedy_exploration', False,
  'Whether to use a greedy policy when doing systematic exploration.')
tf.app.flags.DEFINE_bool(
  'use_baseline', False,
  'Whether to use baseline during policy gradient.')
tf.app.flags.DEFINE_float(
  'min_prob', 0.0,
  ('Minimum probability of a negative'
   'example for it to be punished to avoid numerical issue.'))
tf.app.flags.DEFINE_float(
  'lm_loss_coeff', 0.0,
  'Weight for lm loss.')
tf.app.flags.DEFINE_float(
  'entropy_reg_coeff', 0.0,
  'Weight for entropy regularization.')
tf.app.flags.DEFINE_string(
  'optimizer', 'adam', '.')
tf.app.flags.DEFINE_float(
  'adam_beta1', 0.9, 'adam beta1 parameter.')
tf.app.flags.DEFINE_bool(
  'sample_other', False, 'Whether to use a greedy policy during training.')
tf.app.flags.DEFINE_bool(
  'use_replay_samples_in_train', True,
  'Whether to use replay samples for training.')
tf.app.flags.DEFINE_bool(
  'random_replay_samples', False,
  'randomly pick a replay samples as ML baseline.')
tf.app.flags.DEFINE_bool(
  'use_policy_samples_in_train', False,
  'Whether to use on-policy samples for training.')
tf.app.flags.DEFINE_bool(
  'use_nonreplay_samples_in_train', True,
  'Whether to use a negative samples for training.')
tf.app.flags.DEFINE_integer(
  'n_replay_samples', 5, 'Number of replay samples drawn.')
tf.app.flags.DEFINE_integer(
  'n_policy_samples', 1, 'Number of on-policy samples drawn.')
tf.app.flags.DEFINE_bool(
  'use_top_k_replay_samples', True,
  ('Whether to use the top k most probable (model probability) replay samples'
   ' or to sample from the replay samples.'))
tf.app.flags.DEFINE_bool(
  'use_top_k_policy_samples', False,
  ('Whether to use the top k most probable (from beam search) samples'
   ' or to sample from the replay samples.'))
tf.app.flags.DEFINE_float(
  'fixed_replay_weight', 1, 'Weight for replay samples between 0.0 and 1.0.')
tf.app.flags.DEFINE_bool(
  'use_replay_prob_as_weight', True,
  'Whether or not use replay probability as weight for replay samples.')
tf.app.flags.DEFINE_float(
  'min_replay_weight', 0.1, 'minimum replay weight.')
tf.app.flags.DEFINE_bool(
  'use_importance_sampling', False, '')
tf.app.flags.DEFINE_float(
  'ppo_epsilon', 0.2, '')
tf.app.flags.DEFINE_integer(
  'truncate_replay_buffer_at_n', 5,
  'Whether truncate the replay buffer to the top n highest prob trajs.')
tf.app.flags.DEFINE_bool(
  'use_trainer_prob', True,
  'Whether to supply all the replay buffer for training.')
tf.app.flags.DEFINE_bool(
  'show_log', True,
  'Whether to show logging info.')


# Eval
tf.app.flags.DEFINE_integer(
  'eval_beam_size', 5,
  'Beam size when evaluating on development set.')

tf.app.flags.DEFINE_integer(
  'eval_batch_size', 50,
  'Batch size when evaluating on development set.')

tf.app.flags.DEFINE_bool(
  'eval_only', False, 'only run evaluator.')

tf.app.flags.DEFINE_bool(
  'debug', False, 'Whether to output debug information.')


# Device placement.
tf.app.flags.DEFINE_bool(
  'train_use_gpu', True, 'Whether to output debug information.')
tf.app.flags.DEFINE_integer(
  'train_gpu_id', 0, 'Id of the gpu used for training.')

tf.app.flags.DEFINE_bool(
  'eval_use_gpu', True, 'Whether to output debug information.')
tf.app.flags.DEFINE_integer(
  'eval_gpu_id', 1, 'Id of the gpu used for eval.')

tf.app.flags.DEFINE_bool(
  'actor_use_gpu', True, 'Whether to output debug information.')
tf.app.flags.DEFINE_integer(
  'actor_gpu_start_id', 0,
  'Id of the gpu for the first actor, gpu for other actors will follow.')


# Testing
tf.app.flags.DEFINE_bool(
  'unittest', False, '.')

tf.app.flags.DEFINE_integer(
  'n_opt_step', 1, 'Number of optimization steps per training batch.')

```

**Comment by crazydonkey200** [comment]
This looks like a problem with multiprocessing. Does the original python2 version runs well on your machine?

**Comment by guotong1988** [comment]
I edit 
```
tf.app.flags.DEFINE_integer(
  'n_actors', 30, 'Number of actors for generating samples.')
```
to
```
tf.app.flags.DEFINE_integer(
  'n_actors', 3, 'Number of actors for generating samples.')
```
then Ok
